FROM php:7.1.31-zts-alpine3.9

# Composer
RUN \
    curl -sS https://getcomposer.org/installer | php && \
    mv composer.phar /usr/local/bin/composer && \
    composer self-update && \
    docker-php-ext-install mysqli && \
    docker-php-ext-install pdo_mysql && \
    apk add mariadb-client && \
    mkdir -p /happs
    
WORKDIR /happs
    
COPY src/ /happs/
RUN composer install --no-interaction



 
